ALTER TABLE text_camps
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '💬',
ADD COLUMN IF NOT EXISTS banner_color TEXT DEFAULT '#FF6B00',
ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false;

NOTIFY pgrst, 'reload schema';
