$path = "c:\Users\Anurag\meetra_app\lib\management_dashboard.dart"
$lines = Get-Content $path
$lines1 = $lines[0..716]
$lines2 = $lines[764..($lines.Length-1)]
$newLines = @(
"          Padding(",
"            padding: const EdgeInsets.all(16),",
"            child: Row(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                CircleAvatar(",
"                  radius: 24,",
"                  backgroundImage: NetworkImage(hostAvatar),",
"                  backgroundColor: Colors.white10,",
"                ),",
"                const SizedBox(width: 16),",
"                Expanded(",
"                  child: Column(",
"                    crossAxisAlignment: CrossAxisAlignment.start,",
"                    children: [",
"                      Text(title, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16, color: Colors.white)),",
"                      const SizedBox(height: 4),",
"                      Text('with `$hostName', style: const TextStyle(color: Colors.white54, fontSize: 13)),",
"                      if (location.isNotEmpty) ...[",
"                        const SizedBox(height: 6),",
"                        Row(",
"                          children: [",
"                            const Icon(Icons.location_on, size: 12, color: Colors.white38),",
"                            const SizedBox(width: 4),",
"                            Text(location, style: const TextStyle(color: Colors.white38, fontSize: 12)),",
"                          ],",
"                        ),",
"                      ],",
"                      if (hook.isNotEmpty && isApproved) ...[",
"                        const SizedBox(height: 12),",
"                        Container(",
"                          padding: const EdgeInsets.all(10),",
"                          decoration: BoxDecoration(color: Colors.white.withValues(alpha: 0.03), borderRadius: BorderRadius.circular(10)),",
"                          child: Text('`"`$hook`"', style: const TextStyle(fontStyle: FontStyle.italic, color: Colors.white70, fontSize: 12)),",
"                        ),",
"                      ]",
"                    ],",
"                  ),",
"                ),",
"              ],",
"            ),",
"          ),",
"",
"          if (isApproved && hostId != null)",
"            Padding(",
"              padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),",
"              child: Row(",
"                children: [",
"                  Expanded(",
"                    child: ElevatedButton.icon(",
"                      style: ElevatedButton.styleFrom(",
"                        backgroundColor: themeColor.withValues(alpha: 0.15),",
"                        foregroundColor: themeColor,",
"                        elevation: 0,",
"                        padding: const EdgeInsets.symmetric(vertical: 14),",
"                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),",
"                      ),",
"                      icon: const Icon(Icons.chat_bubble, size: 18),",
"                      label: const Text('Open Chat', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),",
"                      onPressed: () {",
"                        Navigator.push(context, MaterialPageRoute(builder: (_) => ChatDetailScreen(",
"                          targetUserId: hostId!,",
"                          name: hostName,",
"                          avatarUrl: hostAvatar",
"                        )));",
"                      }",
"                    ),",
"                  ),",
"                  if (targetType == 'activity') ...[",
"                    const SizedBox(width: 10),",
"                    Container(",
"                      height: 48, width: 48,",
"                      decoration: BoxDecoration(",
"                        color: Colors.white.withValues(alpha: 0.05),",
"                        borderRadius: BorderRadius.circular(14),",
"                        border: Border.all(color: Colors.white12),",
"                      ),",
"                      child: IconButton(",
"                        icon: const Icon(Icons.info_outline, color: Colors.white),",
"                        onPressed: () {",
"                          Navigator.push(context, MaterialPageRoute(builder: (_) => RushInConsumerDetailView(",
"                            activity: _targetData!,",
"                            onInteraction: () {}, ",
"                          )));",
"                        },",
"                      ),",
"                    ),",
"                  ]",
"                ],",
"              ),",
"            ),",
"        ],",
"      ),",
"    );",
"  }",
"",
"  Widget _buildDismissableCard({required String title, required String msg, required Color color, required IconData icon}) {",
"    return Container(",
"      margin: const EdgeInsets.only(bottom: 12),",
"      padding: const EdgeInsets.all(16),",
"      decoration: BoxDecoration(",
"        color: color.withValues(alpha: 0.05),",
"        borderRadius: BorderRadius.circular(16),",
"        border: Border.all(color: color.withValues(alpha: 0.3)),",
"      ),",
"      child: Row(",
"        children: [",
"          Container(",
"            padding: const EdgeInsets.all(10),",
"            decoration: BoxDecoration(color: color, shape: BoxShape.circle),",
"            child: Icon(icon, color: Colors.white, size: 18),",
"          ),",
"          const SizedBox(width: 16),",
"          Expanded(",
"            child: Column(",
"              crossAxisAlignment: CrossAxisAlignment.start,",
"              children: [",
"                Text(title, style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: color)),",
"                Text(msg, style: const TextStyle(color: Colors.white54, fontSize: 12)),",
"              ],",
"            ),",
"          ),",
"          TextButton(",
"            onPressed: () async {",
"              await Supabase.instance.client.from('requests').delete().eq('id', widget.request['id']);",
"            },",
"            child: const Text('DISMISS', style: TextStyle(color: Colors.white38, fontSize: 11, fontWeight: FontWeight.bold)),",
"          ),",
"        ],",
"      ),",
"    );",
"  }",
"}"
)
Set-Content -Path $path -Value ($lines1 + $newLines + $lines2)
